#!/bin/sh

echo "sample-test:"

verify() {
    if ./stk.sh samples/$1.stkn tmp.out && ./tmp.out | diff samples/$1.expected - ;
    then
        echo $1 "pass."
    else
        echo $1 "failed."
    fi
}

verify empty
verify write
verify fib
verify nest-func
verify return-void
